"""windaudit (sergeievland/windaudit @aba5633) patch-graph audit for SwitchBench v1, two modes.

default  = v0's run (run_windaudit.py): scripts/wide_patch_audit.py unchanged, WIDE_ATTACHMENT_GAP=1
           (the attachment-gap transport its README reports as the corrected construction), attachment
           tolerance 2.5 vx; patches with < 2 attached annotation points are silent by construction.
intended = "attachment gap widened per its docs" (protocol P1 (prereg/switchbench_v1.md), author-intended mode): the harness fixes
           the patch attachment tolerance at 2.5 vx and documents no wider value for it, so the widest
           same-sheet tolerance its docs use is taken: r_same = 0.45 D with D = 23.30 vx (METHODS.md
           sensitivity sweep {0.25, 0.35, 0.45} D; README calibration), i.e. 10.485 vx. A copy of the
           pinned harness is generated with only that constant changed (asserted substitutions), so its
           cache keys differ from the default run's. Everything else as default.
Alarm on the unverified patch U (v0 rule): the corrected solver ('after') edits an edge incident to U;
alarm location = U's attachment point of that edge.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys

import numpy as np

from . import annot, geom
from .sanity import lineage

WA = os.environ.get("SWITCHBENCH_EXT", "ext") + "/windaudit"
V1 = geom.REPO / "data" / "switchbench_v1"
TOL = {"default": 2.5, "intended": round(0.45 * 23.30, 3)}
SCRIPT = {"default": "scripts/wide_patch_audit.py", "intended": "scripts/wide_patch_audit_tol10485.py"}


def intended_script():
    """Script copy for this process: WA_SCRIPT_VARIANT=b selects a second generated copy, identical except
    for its header line, so two concurrent intended-mode processes never share cache keys (the harness keys
    its cache on its own file bytes). Results are identical; only the cache is separate."""
    v = os.environ.get("WA_SCRIPT_VARIANT", "")
    return SCRIPT["intended"].replace(".py", f"_{v}.py") if v else SCRIPT["intended"], v


def make_intended_script(variant=""):
    src = open(f"{WA}/scripts/wide_patch_audit.py").read()
    t = TOL["intended"]
    subs = [("np.all((point_xyz>=lower-2.501)&(point_xyz<=upper+2.501),axis=1)",
             f"np.all((point_xyz>=lower-{t + 0.001})&(point_xyz<=upper+{t + 0.001}),axis=1)"),
            ("hit=surface.project(points[pi]['p'],2.5)", f"hit=surface.project(points[pi]['p'],{t})")]
    for a, b in subs:
        assert src.count(a) == 1, a
        src = src.replace(a, b)
    hdr = (f'# GENERATED by scrolls tools/switchbench/run_windaudit_v1.py from wide_patch_audit.py @aba5633:\n'
           f'# only the point attachment tolerance changed, 2.5 -> {t} vx (0.45 D, windaudit METHODS.md sweep).\n'
           + (f'# copy {variant}: identical logic, separate cache keys for a concurrent process.\n' if variant else ''))
    path = SCRIPT["intended"].replace(".py", f"_{variant}.py") if variant else SCRIPT["intended"]
    open(f"{WA}/{path}", "w").write(hdr + src)


def run(nm, P, N, mode="default"):
    out_dir = V1 / "detect" / f"windaudit_{mode}"
    f = out_dir / f"{nm}.json"
    if f.exists():
        return json.load(open(f))
    out_dir.mkdir(parents=True, exist_ok=True)
    old = annot.ATTACH
    annot.ATTACH = TOL[mode]
    try:
        att = annot.attach(P, N)
    finally:
        annot.ATTACH = old
    rec = dict(tool="windaudit", mode=mode, tolerance_vx=TOL[mode], patch=nm, n_attached=len(att), alarms_xyz=[])
    if len(att) < 2:
        rec["verdict"] = "silent: fewer than 2 annotation points attach"
        json.dump(rec, open(f, "w"))
        return rec
    script = SCRIPT[mode]
    if mode == "intended":
        script, variant = intended_script()
        if not os.path.exists(f"{WA}/{script}"):
            make_intended_script(variant)
        rec["script"] = script
    vi = geom.VerifiedIndex()
    lo = np.nanmin(P.reshape(-1, 3), 0); hi = np.nanmax(P.reshape(-1, 3), 0)
    lin = lineage(nm)
    names = [v for v in vi.overlapping(lo, hi, pad=300.0) if lineage(v) != lin]
    tmp = V1 / "detect" / f"windaudit_tmp_{mode}" / nm
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True)
    os.symlink(geom.DATA / "unverified_patches" / nm, tmp / nm)
    for v in names:
        os.symlink(geom.DATA / "verified_patches" / v, tmp / v)
    out = V1 / "detect" / f"windaudit_out_{mode}" / nm
    env = dict(os.environ, WIDE_ATTACHMENT_GAP="1")
    p = subprocess.run([f"{WA}/.venv/bin/python", script, str(tmp),
                        "upstream/villa/find_inconsistent_windings.py",
                        "out/wide_solver/spiral-fitting/find_inconsistent_windings.py", str(out), str(geom.DATA)],
                       cwd=WA, env=env, capture_output=True, text=True, timeout=3600)
    rec.update(returncode=p.returncode, n_verified_in_folder=len(names), tail=(p.stdout + p.stderr)[-600:])
    if p.returncode != 0 or not (out / "measured_edges.json").exists():
        rec["verdict"] = "error"
        shutil.rmtree(tmp, ignore_errors=True)
        json.dump(rec, open(f, "w"))
        return rec
    edges = json.load(open(out / "measured_edges.json"))
    after = json.load(open(out / "after_full.json"))
    changed = {(e["rel_pcl_id"], frozenset((e["from_point_id"], e["to_point_id"]))) for e in after.get("edges", [])}
    hits = []
    for e in edges:
        key = (e["pcl_id"], frozenset((e["from_point_id"], e["to_point_id"])))
        if key in changed and nm in (e["P"], e["R"]):
            ij = e["from_ij"] if e["P"] == nm else e["to_ij"]
            i, j = int(np.floor(ij[0])), int(np.floor(ij[1]))
            if 0 <= i < P.shape[0] and 0 <= j < P.shape[1] and np.isfinite(P[i, j]).all():
                hits.append(P[i, j].tolist())
    init = json.load(open(out / "initial_graph.json"))
    rec.update(verdict="alarm" if hits else "clean", alarms_xyz=hits,
               initial_inconsistent=init.get("inconsistent_non_tree_edges"),
               u_in_graph=any(nm in (e["P"], e["R"]) for e in edges))
    shutil.rmtree(tmp, ignore_errors=True)
    json.dump(rec, open(f, "w"))
    return rec


if __name__ == "__main__":
    mode = sys.argv[1]
    for nm in sys.argv[2:]:
        d = geom.DATA / "unverified_patches" / nm
        P = geom.load_tifxyz(d)
        N = geom.orient_outward(P, geom.grid_normals(P))
        print(json.dumps(run(nm, P, N, mode))[:300])
